# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Sessões ativadas, se necessário
    session: true

     # Ativando o Rate Limiter
    rate_limiter:
        enabled: true
        limiters:
            api:
                policy: 'sliding_window' # Política de limite (sliding_window ou fixed_window)
                limit: 100               # Máximo de requisições permitidas
                interval: '1 minute'     # Intervalo de tempo

# Configuração de teste, se necessário
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

           
