# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Sessões ativadas, se necessário
    session: true

# Configuração de teste, se necessário
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

           
